version: "3.9"

services:
  worker-1:
    build:
      context: .
    container_name: worker-1
    network_mode: "host"
    environment:
      - KAFKA_BROKER=localhost:9092

  worker-2:
    build:
      context: .
    container_name: worker-2
    network_mode: "host"
    environment:
      - KAFKA_BROKER=localhost:9092
